name: habits_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  flutter_carousel_widget: ^3.1.0
  device_preview_plus: ^2.4.7
  fl_chart: 0.68.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  cloud_firestore: ^6.0.1
  toastification: ^3.0.3

# ////////////////////////////////////// //////////////////
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6   # ✅ moved here

#  ///////////////////////////////////////////////////////
flutter:
  uses-material-design: true
  assets:
    - assets/                  # ✅ corrected asset path

#///////////////////////////////
# ✅ Add splash screen config
flutter_native_splash:
  color: "#ffffff"                 # background color
  image: assets/Generated Image September 16, 2025 - 1_06AM.png       # your logo (corrected path)
  #branding: lib/assets/brand.png   # optional (small image at bottom)
  android: true
  ios: true
  web: false

  # Optional settings
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
